PROG=		activate-bsd
MAN=

.PATH: ${.CURDIR}/src

SRCS=		$(wildcard *.c)

CFLAGS+=	-I/usr/local/include
CFLAGS+=	-I/usr/local/include/cairo
CFLAGS += \
	$(CFLAGS) \
	$(shell pkg-config --cflags --libs x11 xfixes xinerama) \
	$(shell pkg-config --cflags --libs cairo)

LDFLAGS+=	-L/usr/local/lib

LDADD+=		-lX11
LDADD+=		-lXfixes
LDADD+=		-lXinerama
LDADD+=		-lcairo

.include <bsd.prog.mk>
